### ISSUE TITLE
CSS for code blocks is not behaving

### ISSUE THREAD

**Issue by flytzen** [flytzen/blog#2]
Hi @squidgemonster I wonder if I could beg another favour? I am realising just how rubbish my CSS skills are.... I will own you big time! 

When 
I put a code block in my posts, it doesn't render quite right. I hacked something in order to make a one-line render sort-of-correctly in this post: https://www.lytzen.name/2018/05/08/Comos-db-token-failure.html

But it doesn't work properly with multi-line posts. If you pull master and run `bundle exec jekyll serve --draft` then you'll see two posts, one is CSS test, the other is "Hierarchy ID for fun and performance". The former is a better example, but the second has a two-liner but only one line is visible.

**Comment by squidgemonster** [comment]
One the case my friend :)
